src/main/java/com/meiyuetao/o2o/entity/SharedPosts.java
package com.meiyuetao.o2o.entity;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import lab.s2jh.core.annotation.MetaData;

import org.apache.commons.lang3.StringUtils;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.meiyuetao.myt.core.entity.MytBaseEntity;
import com.meiyuetao.myt.customer.entity.CustomerProfile;
import com.meiyuetao.myt.md.entity.ActivityR2Object.ObjectTypeEnum;
import com.meiyuetao.myt.md.entity.Commodity;

@MetaData("优蜜美店用户晒单")
@Entity
@Table(name = "sns_shared_posts")
@Cache(usage = CacheConcurrencyStrategy.NONE)
public class SharedPosts extends MytBaseEntity {
    private static final long serialVersionUID = 1L;
    @MetaData("对象类型")
    private ObjectTypeEnum objectType;
    @MetaData("对象商品")
    private Commodity object;
    @MetaData("对象名字")
    private String objectName;
    @MetaData("对象图片")
    private String objectPic;
    @MetaData("对象值")
    private String objectExtValue;
    @MetaData("对象值1")
    private String objectExtValue1;
    @MetaData("晒单内容")
    private String postsContent;
    @MetaData("晒单图1")
    private String postsSharedPic1;
    @MetaData("晒单图2")
    private String postsSharedPic2;
    @MetaData("晒单图3")
    private String postsSharedPic3;
    @MetaData("回复数")
    private Integer postsReplyCount;
    @MetaData("点赞数")
    private Integer postsLoveCount;
    @MetaData("用户")
    private CustomerProfile user;
    @MetaData("审核状态")
    private PostsStatusEnum postsStatus;

    // public enum ObjectTypeEnum {
    // @MetaData("商品")
    // COMMODITY;
    // }

    public enum PostsStatusEnum {
        @MetaData("用户发布")
        PUBLISH,

        @MetaData("通过审核")
        PASS,

        @MetaData("封杀")
        KILL;
    }

    @Enumerated(EnumType.STRING)
    @Column(name = "object_type")
    @JsonProperty
    public ObjectTypeEnum getObjectType() {
        return objectType;
    }

    public void setObjectType(ObjectTypeEnum objectType) {
        this.objectType = objectType;
    }

    @ManyToOne(cascade = CascadeType.DETACH)
    @JoinColumn(name = "object_sid")
    @JsonProperty
    public Commodity getObject() {
        return object;
    }

    public void setObject(Commodity object) {
        this.object = object;
    }

    @Column(name = "object_name")
    @JsonProperty
    public String getObjectName() {
        return objectName;
    }

    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }

    @Column(name = "object_pic")
    @JsonProperty
    public String getObjectPic() {
        return objectPic;
    }

    public void setObjectPic(String objectPic) {
        this.objectPic = objectPic;
    }

    @Column(name = "object_ext_value")
    @JsonProperty
    public String getObjectExtValue() {
        return objectExtValue;
    }

    public void setObjectExtValue(String objectExtValue) {
        this.objectExtValue = objectExtValue;
    }

    @Column(name = "object_ext_value1")
    @JsonProperty
    public String getObjectExtValue1() {
        return objectExtValue1;
    }

    public void setObjectExtValue1(String objectExtValue1) {
        this.objectExtValue1 = objectExtValue1;
    }

    @Column(name = "posts_content")
    @JsonProperty
    public String getPostsContent() {
        return postsContent;
    }

    public void setPostsContent(String postsContent) {
        this.postsContent = postsContent;
    }

    @Column(name = "posts_shared_pic1")
    @JsonProperty
    public String getPostsSharedPic1() {
        return postsSharedPic1;
    }

    public void setPostsSharedPic1(String postsSharedPic1) {
        this.postsSharedPic1 = postsSharedPic1;
    }

    @Column(name = "posts_shared_pic2")
    @JsonProperty
    public String getPostsSharedPic2() {
        return postsSharedPic2;
    }

    public void setPostsSharedPic2(String postsSharedPic2) {
        this.postsSharedPic2 = postsSharedPic2;
    }

    @Column(name = "posts_shared_pic3")
    @JsonProperty
    public String getPostsSharedPic3() {
        return postsSharedPic3;
    }

    public void setPostsSharedPic3(String postsSharedPic3) {
        this.postsSharedPic3 = postsSharedPic3;
    }

    @Column(name = "posts_reply_count")
    @JsonProperty
    public Integer getPostsReplyCount() {
        return postsReplyCount;
    }

    public void setPostsReplyCount(Integer postsReplyCount) {
        this.postsReplyCount = postsReplyCount;
    }

    @Column(name = "posts_love_count")
    @JsonProperty
    public Integer getPostsLoveCount() {
        return postsLoveCount;
    }

    public void setPostsLoveCount(Integer postsLoveCount) {
        this.postsLoveCount = postsLoveCount;
    }

    @OneToOne(cascade = CascadeType.DETACH)
    @JoinColumn(name = "user_sid")
    @JsonProperty
    public CustomerProfile getUser() {
        return user;
    }

    public void setUser(CustomerProfile user) {
        this.user = user;
    }

    @Enumerated(EnumType.STRING)
    @Column(name = "posts_status")
    @JsonProperty
    public PostsStatusEnum getPostsStatus() {
        return postsStatus;
    }

    public void setPostsStatus(PostsStatusEnum postsStatus) {
        this.postsStatus = postsStatus;
    }

    @Transient
    @JsonProperty
    public String getDisplay() {
        if (StringUtils.isNotBlank(this.objectName)) {
            return this.objectName;
        }
        return id.toString();
    }

}

src/main/webapp/WEB-INF/template/freemarker/CALL_CENTER_INFO.ftl
<!doctype html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="Generator" content="EditPlus®">
  <meta name="Author" content="">
  <meta name="Keywords" content="">
  <meta name="Description" content="">
  <title>美月淘</title>
 </head>
 <body>

<table width="680" cellpadding="0" cellspacing="0">
            <tbody><tr>
                <td>
                    <img src="http://img.iyoubox.com/GetFileByCode.aspx?code=E8043381F87CD3057E1F73394F03BAD4" border="0" usemap="#Map">
                </td>
            </tr>
</tbody></table>       
<map name="Map">
  <area shape="rect" coords="591,26,627,61" target="_blank" href="http://e.weibo.com/u/2529585731">
  <area shape="rect" coords="627,26,664,61" target="_blank" href="http://t.qq.com/meiyuetaoV">
</map>
</body>
</html>

src/main/webapp/WEB-INF/template/freemarker/DELIVERY_NOTIFY_EMAIL.ftl

<table width="680" cellpadding="0" cellspacing="0">
            <tbody><tr>
                <td>
                    <img src="http://img.iyoubox.com/GetFileByCode.aspx?code=E8043381F87CD3057E1F73394F03BAD4" border="0" usemap="#Map">
                </td>
            </tr>
            <tr>
                <td>
                    <table style="margin-top: 5px;" cellpadding="0" cellspacing="0">
                        <tbody><tr>
                            <td style="height: 19px; overflow: hidden; background: url(http://img.iyoubox.com/GetFileByCode/14984E607455F033FE56C30BF01125F5) no-repeat">
                            </td>
                        </tr>
                        <tr>
                            <td style="background: url(http://img.iyoubox.com/GetFileByCode/D88F61341715990677B10F3D12DDD1DB) repeat-y left center;
                                padding: 5px 24px; width: 680px;">
                                <p class="fontstyle_1" style="font-size: 16px; line-height: 29px; color: #333333;
                                    margin: 0 10px; font-weight: bold;">
                                    亲爱的 ${customerProfile.display} ：</p>
                                <p class="fontstyle_2" style="text-indent: 2em; font-size: 16px; line-height: 29px;
                                    color: #333333; margin: 0 10px;">
                                    您好！</p>
                                <p class="fontstyle_2" style="text-indent: 2em; font-size: 16px; line-height: 29px;
                                    color: #333333; margin: 0 10px;">
                                        <span>感谢您在美月淘购物! 我们很高兴地通知您, 您订购的商品已经发货。
								</span></p><p class="fontstyle_2" style="text-indent: 2em; font-size: 16px; line-height: 29px;
                                    color: #333333; margin: 0 10px;">
                                    物流公司: ${saleDelivery.logistics.abbr}</p>
									<p class="fontstyle_2" style="text-indent: 2em; font-size: 16px; line-height: 29px;
                                    color: #333333; margin: 0 10px;">物流单号:${saleDelivery.logisticsNo}</p>
                                <p class="fontstyle_2" style="margin: 0 10px; margin-left: 380px; margin-top: 20px;
                                    text-indent: 2em; font-size: 16px; line-height: 29px; color: #333333;">
                                    美月淘-哎呦盒子团队敬上</p>
                                <p class="fontstyle_2" style="margin: 0 10px; margin-left: 380px; text-indent: 2em;
                                    font-size: 16px; line-height: 29px; color: #333333;">
                                    ${todayDate?string("yyyy年MM月dd日")}</p>
                                <div>
                                        <table width="620" border="0" cellpadding="0" cellspacing="0" class="goods_yuding" style="margin-top: 0px;">
                                            <tbody><tr>
                                                <td width="150" height="25" align="left" valign="middle" bgcolor="#f7f7f7">配送详情
                                                </td>
												 <td width="300" height="25" align="right" valign="middle" bgcolor="#f7f7f7">
                                                    &nbsp;
                                                </td>
												 <td width="170" height="25" align="right" valign="middle" bgcolor="#f7f7f7">
                                                 </td>
                                               
                                            </tr>
											<#list saleDeliveryDetails as item>
                                            <tr>
                                                <td >
												    <div style="overflow: hidden; height: auto; margin: 5px; ">
													  <a href="http://www.meiyuetao.com/product/"+${item.commodity.id?c}+".html">
                                                                    <img style="border: 1px solid #fe638e;overflow: hidden;height: 90px;" width="102" height="90" src="http://img.iyoubox.com/GetFileByCode/${item.commodity.smallPic}">
                                                                </a>
													</div>
												</td>
												<td > 
													<p style=" text-align: center; color: #666; font-size: 14px; overflow: hidden;
                                                                    text-indent: 0;"> <a href="http://www.meiyuetao.com/product/"+${item.commodity.id?c}+".html">
                                                                    ${item.commodity.title}</a></p>
                                                </td>
												<td >
													 <p style=" text-align: center; color: #666; font-size: 14px; overflow: hidden;
                                                                    text-indent: 0;">
                                                                    数量：${item.quantity}</p>
                                                </td>
												
											 </tr>
											 </#list>
                                        </tbody></table>

                                </div>
                                <div class="fontstyle_4" style="background-color: #fff8df; margin-top: 45px; width: 627px;
                                    margin: 45px auto 0 0; clear: both; padding: 0 5px; line-height: 30px; color: #333333;
                                    font-size: 12px;">
                                    注意：您可以在<span style="color: #40b6f7; font-weight: bold;"> <a href="http://www.meiyuetao.com/MYT_Order/Index">
                                        我的订单</a> </span>中查看订单详情。</div>
                            </td>
                        </tr>
                        <tr>
                            <td style="background: url(http://img.iyoubox.com/GetFileByCode/A266F944DB0102EBCD602741CFB1C011) no-repeat left center;
                                width: 680px; height: 17px;">
                            </td>
                        </tr>
                    </tbody></table>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="food" style="width: 641px; padding: 5px; margin: 10px 24px 0 15px; background-color: #fff4f7;
                        border: 1px dashed #d6d6d6; border-bottom: none;">
                        <p style="text-align: right; font-size: 14px; color: #999999;">
                            需要帮助？有建议？有反馈？请点击<a href="http://www.meiyuetao.com/Help/Index/?StaticId=MHelp.FAQ" style="color: #3f7f99;"><strong> 用户帮助及反馈 </strong></a>或拨打：400-898-6221</p>
                        <p style="text-align: right; font-size: 12px; color: #333333; margin-top: 15px;">
                            想要了解更多关于什么是按月预定、美月淘及哎呦盒子的信息，请访问：<a href="http://www.meiyuetao.com/Help/Index/?StaticId=MHelp.FAQ" style="color: #3f7f99;"> 入门指南 </a>获得更多的了解</p>
                        <p style="text-align: right; font-size: 12px; color: #333333;">
                            这是一封自动生成的邮件，请不要回复，因为此发件人不能接收邮件</p>
                        <p style="text-align: right; font-size: 12px; color: #333333;">
                            如果您不想收到此类邮件， 请登陆<a href="http://www.meiyuetao.com" style="color: #3f7f99;">美月淘网站</a></p>
                        <p style="text-align: right; font-size: 12px; color: #333333;">
                            我们不会出售或分享您的邮件地址给任何第三方</p>
                    </div>
                </td>
            </tr>
        </tbody></table>
<map name="Map">
  <area shape="rect" coords="591,26,627,61" target="_blank" href="http://e.weibo.com/u/2529585731">
  <area shape="rect" coords="627,26,664,61" target="_blank" href="http://t.qq.com/meiyuetaoV">
</map>

src/main/webapp/WEB-INF/template/freemarker/DELIVERY_NOTIFY_SMS.ftl
亲爱的 ${customerProfile.display}顾客，您在美月淘购物的包裹${saleDelivery.referenceVoucher}已发货，<#if saleDelivery.deliveryType=="INNER_EXPRESS">快件由申通快递发出，单号： ${saleDelivery.logisticsNo} 快件信息可登陆 ${saleDelivery.logistics.display}网站直接查询<#elseif saleDelivery.deliveryType=="EXPRESS">由邮政特快专递发出，单号： ${saleDelivery.logisticsNo} 快件信息可登陆http://www.11183.com.cn/mailtracking/you_jian_cha_xun.html;jsessionid=LMFWJgjLJn4Yhv2pv8HwBhKhqnLHzLzvv1dydn9ynxQLMDXMp4M5!-110892546查看<#elseif saleDelivery.deliveryType=="POST">快件由中国邮政国际给据发出，单号： ${saleDelivery.logisticsNo} 快件信息可登陆http://intmail.183.com.cn/查询<#elseif saleDelivery.deliveryType=="DHL">快件由德国dhl国际快递给据发出，单号： ${saleDelivery.logisticsNo} 快件信息可登陆http://www.dhl.de/en.html查询<#elseif saleDelivery.deliveryType=="TNT">快件由荷兰TNT皇家邮政给据发出，单号： ${saleDelivery.logisticsNo} 快件信息可登陆http://www.postnlparcels.com/enl查询<#else>NONE</#if>，如有疑问，请致电美月淘服务热线：4008986221。

src/main/webapp/WEB-INF/template/freemarker/FAST_REGISTER_BY_MOBILE_SMS.ftl
您好，很高兴为您服务，您可以用本手机号（${loginid}）登录美月淘网站，密码为：${password}。客服电话：400-898-6221

src/main/webapp/WEB-INF/template/freemarker/ORDER_CANCEL_NOTIFY_EMAIL.ftl
<!doctype html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="Generator" content="EditPlus®">
  <meta name="Author" content="">
  <meta name="Keywords" content="">
  <meta name="Description" content="">
  <title>美月淘</title>
 </head>
 <body>

<table width="680" cellpadding="0" cellspacing="0">
            <tbody><tr>
                <td>
                    <img src="http://img.iyoubox.com/GetFileByCode.aspx?code=E8043381F87CD3057E1F73394F03BAD4" border="0" usemap="#Map">
                </td>
            </tr>
            <tr>
                <td>
                    <table style="margin-top: 5px;" cellpadding="0" cellspacing="0">
                        <tbody><tr>
                            <td style="height: 19px; overflow: hidden; background: url(http://img.iyoubox.com/GetFileByCode/14984E607455F033FE56C30BF01125F5) no-repeat">
                            </td>
                        </tr>
                        <tr>
                            <td style="background: url(http://img.iyoubox.com/GetFileByCode/D88F61341715990677B10F3D12DDD1DB) repeat-y left center;
                                padding: 5px 24px; width: 680px;">
                                <p class="fontstyle_1" style="font-size: 16px; line-height: 29px; color: #333333;
                                    margin: 0 10px; font-weight: bold;">
                                    亲爱的 ${customerProfile.display} ：</p>
                                <p class="fontstyle_2" style="text-indent: 2em; font-size: 16px; line-height: 29px;
                                    color: #333333; margin: 0 10px;">
                                    您好！</p>
                                <p class="fontstyle_2" style="text-indent: 2em; font-siz与e: 16px; line-height: 29px;
                                    color: #333333; margin: 0 10px;">
                                        <span>您的一笔订单已取消。订单号：${boxOrder.orderSeq}
								</span></p>
                                <p class="fontstyle_2" style="margin: 0 10px; margin-left: 380px; margin-top: 20px;
                                    text-indent: 2em; font-size: 16px; line-height: 29px; color: #333333;">
                                   	 美月淘-哎呦盒子</p>
                                <p class="fontstyle_2" style="margin: 0 10px; margin-left: 380px; text-indent: 2em;
                                    font-size: 16px; line-height: 29px; color: #333333;">
                                    ${todayDate?string("yyyy年MM月dd日")}</p>
                               <div class="fontstyle_4" style="background-color: #fff8df; margin-top: 45px; width: 627px;
                                    margin: 45px auto 0 0; clear: both; padding: 0 5px; line-height: 30px; color: #333333;
                                    font-size: 12px;">
                                    注意：您可以在<span style="color: #40b6f7; font-weight: bold;"> <a href="http://www.meiyuetao.com/MYT_Order/Index">
                                        我的订单</a> </span>中查看订单详情。</div>
                            </td>
                        </tr>
                        <tr>
                            <td style="background: url(http://img.iyoubox.com/GetFileByCode/A266F944DB0102EBCD602741CFB1C011) no-repeat left center;
                                width: 680px; height: 17px;">
                            </td>
                        </tr>
                    </tbody></table>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="food" style="width: 641px; padding: 5px; margin: 10px 24px 0 15px; background-color: #fff4f7;
                        border: 1px dashed #d6d6d6; border-bottom: none;">
                        <p style="text-align: right; font-size: 14px; color: #999999;">
                            需要帮助？有建议？有反馈？请点击<a href="http://www.meiyuetao.com/Help/Index/?StaticId=MHelp.FAQ" style="color: #3f7f99;"><strong> 用户帮助及反馈 </strong></a>或拨打：400-898-6221</p>
                        <p style="text-align: right; font-size: 12px; color: #333333; margin-top: 15px;">
                            想要了解更多关于什么是按月预定、美月淘及哎呦盒子的信息，请访问：<a href="http://www.meiyuetao.com/Help/Index/?StaticId=MHelp.FAQ" style="color: #3f7f99;"> 入门指南 </a>获得更多的了解</p>
                        <p style="text-align: right; font-size: 12px; color: #333333;">
                            这是一封自动生成的邮件，请不要回复，因为此发件人不能接收邮件</p>
                        <p style="text-align: right; font-size: 12px; color: #333333;">
                            如果您不想收到此类邮件， 请登陆<a href="http://www.meiyuetao.com" style="color: #3f7f99;">美月淘网站</a></p>
                        <p style="text-align: right; font-size: 12px; color: #333333;">
                            我们不会出售或分享您的邮件地址给任何第三方</p>
                    </div>
                </td>
            </tr>
        </tbody></table>
<map name="Map">
  <area shape="rect" coords="591,26,627,61" target="_blank" href="http://e.weibo.com/u/2529585731">
  <area shape="rect" coords="627,26,664,61" target="_blank" href="http://t.qq.com/meiyuetaoV">
</map>
</body>
</html>

src/main/webapp/WEB-INF/template/freemarker/PAY_NOTIFY_EMAIL.ftl
<!doctype html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="Generator" content="EditPlus®">
  <meta name="Author" content="">
  <meta name="Keywords" content="">
  <meta name="Description" content="">
  <title>Document</title>
 </head>
 <body>

<table width="680" cellpadding="0" cellspacing="0">
            <tbody><tr>
                <td>
                    <img src="http://img.iyoubox.com/GetFileByCode.aspx?code=E8043381F87CD3057E1F73394F03BAD4" border="0" usemap="#Map">
                </td>
            </tr>
            <tr>
                <td>
                    <table style="margin-top: 5px;" cellpadding="0" cellspacing="0">
                        <tbody><tr>
                            <td style="height: 19px; overflow: hidden; background: url(http://img.iyoubox.com/GetFileByCode/14984E607455F033FE56C30BF01125F5) no-repeat">
                            </td>
                        </tr>
                        <tr>
                            <td style="background: url(http://img.iyoubox.com/GetFileByCode/D88F61341715990677B10F3D12DDD1DB) repeat-y left center;
                                padding: 5px 24px; width: 680px;">
                                <p class="fontstyle_1" style="font-size: 16px; line-height: 29px; color: #333333;
                                    margin: 0 10px; font-weight: bold;">
                                    亲爱的 ${customerProfile.display} ：</p>
                                <p class="fontstyle_2" style="text-indent: 2em; font-size: 16px; line-height: 29px;
                                    color: #333333; margin: 0 10px;">
                                    您好！</p>
                                <p class="fontstyle_2" style="text-indent: 2em; font-size: 16px; line-height: 29px;
                                    color: #333333; margin: 0 10px;">
                                        <span>您在美月淘预约订购的${reserveDeliveryTime?string("yyyy年MM月dd日")}发货的商品，我们已经为您备货完毕，提醒您及时付款。订单号:${boxOrder.orderSeq}
								</span></p><p class="fontstyle_2" style="text-indent: 2em; font-size: 16px; line-height: 29px;
                                    color: #333333; margin: 0 10px;">
                                    祝您购物愉快！</p>
                                <p class="fontstyle_2" style="margin: 0 10px; margin-left: 380px; margin-top: 20px;
                                    text-indent: 2em; font-size: 16px; line-height: 29px; color: #333333;">
                                    美月淘-哎呦盒子团队敬上</p>
                                <p class="fontstyle_2" style="margin: 0 10px; margin-left: 380px; text-indent: 2em;
                                    font-size: 16px; line-height: 29px; color: #333333;">
                                    ${todayDate?string("yyyy年MM月dd日")}</p>
                                <div>
                                        <table width="620" border="0" cellpadding="0" cellspacing="0" class="goods_yuding" style="margin-top: 0px;">
                                            <tbody><tr>
                                                <td width="150" height="25" align="left" valign="middle" bgcolor="#f7f7f7">待付款商品
                                                </td>
												 <td width="250" height="25" align="right" valign="middle" bgcolor="#f7f7f7">
                                                    &nbsp;
                                                </td>
												 <td width="120" height="25" align="right" valign="middle" bgcolor="#f7f7f7">
                                                   
                                                </td>
                                                <td width="150" height="25" align="right" valign="middle" bgcolor="#f7f7f7">
                                                     总计：￥${boxOrderDetail.actualAmount?default(0.00)} 元
                                                </td>
                                            </tr>
											<#list boxOrderDetailCommodities as item>
                                            <tr>
                                                <td >
												    <div style="overflow: hidden; height: auto; margin: 5px; ">
													  <a href="http://www.meiyuetao.com/product/${item.commodity.id?c}.html">
                                                                    <img style="border: 1px solid #fe638e;overflow: hidden;height: 90px;" width="102" height="90" src="http://img.iyoubox.com/GetFileByCode/${item.commodity.smallPic}">
                                                                </a>
													</div>
												</td>
												<td > 
													<p style=" text-align: center; color: #666; font-size: 14px; overflow: hidden;
                                                                    text-indent: 0;"> <a href="http://www.meiyuetao.com/product/${item.commodity.id?c}.html">
                                                                    ${item.commodity.title}</a></p>
                                                </td>
												<td >
													 <p style=" text-align: center; color: #666; font-size: 14px; overflow: hidden;
                                                                    text-indent: 0;">
                                                                   	 数量：${item.quantity}</p>
                                                </td>
												<td > 
													 <p style=" text-align: center; color: #666; font-size: 14px; overflow: hidden;
                                                                    text-indent: 0;">
                                                                  	 ￥${item.actualAmount?default(0.00)}
                                                </td>
											 </tr>
											 </#list>
                                        </tbody></table>

                                </div>
                                <div class="fontstyle_4" style="background-color: #fff8df; margin-top: 45px; width: 627px;
                                    margin: 45px auto 0 0; clear: both; padding: 0 5px; line-height: 30px; color: #333333;
                                    font-size: 12px;">
                                    注意：您可以在<span style="color: #40b6f7; font-weight: bold;"> <a href="http://www.meiyuetao.com/MYT_Order/Index">
                                        我的订单</a> </span>中查看订单详情。</div>
                            </td>
                        </tr>
                        <tr>
                            <td style="background: url(http://img.iyoubox.com/GetFileByCode/A266F944DB0102EBCD602741CFB1C011) no-repeat left center;
                                width: 680px; height: 17px;">
                            </td>
                        </tr>
                    </tbody></table>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="food" style="width: 641px; padding: 5px; margin: 10px 24px 0 15px; background-color: #fff4f7;
                        border: 1px dashed #d6d6d6; border-bottom: none;">
                        <p style="text-align: right; font-size: 14px; color: #999999;">
                            需要帮助？有建议？有反馈？请点击<a href="http://www.meiyuetao.com/Help/Index/?StaticId=MHelp.FAQ" style="color: #3f7f99;"><strong> 用户帮助及反馈 </strong></a>或拨打：400-898-6221</p>
                        <p style="text-align: right; font-size: 12px; color: #333333; margin-top: 15px;">
                            想要了解更多关于什么是按月预定、美月淘及哎呦盒子的信息，请访问：<a href="http://www.meiyuetao.com/Help/Index/?StaticId=MHelp.FAQ" style="color: #3f7f99;"> 入门指南 </a>获得更多的了解</p>
                        <p style="text-align: right; font-size: 12px; color: #333333;">
                            这是一封自动生成的邮件，请不要回复，因为此发件人不能接收邮件</p>
                        <p style="text-align: right; font-size: 12px; color: #333333;">
                            如果您不想收到此类邮件， 请登陆<a href="http://www.meiyuetao.com" style="color: #3f7f99;">美月淘网站</a></p>
                        <p style="text-align: right; font-size: 12px; color: #333333;">
                            我们不会出售或分享您的邮件地址给任何第三方</p>
                    </div>
                </td>
            </tr>
        </tbody></table>
<map name="Map">
  <area shape="rect" coords="591,26,627,61" target="_blank" href="http://e.weibo.com/u/2529585731">
  <area shape="rect" coords="627,26,664,61" target="_blank" href="http://t.qq.com/meiyuetaoV">
</map>
</body>
</html>